### ISSUE TITLE
ワープ時にエラーが発生

### ISSUE THREAD

**Issue by popkechupki** [CosmoSunriseServerPluginEditorsTeam/AdvancedWarpSystem#1]
10:31:08 [CRITICAL] "'AdvancedWarpSystem v1.0.0'に'cn.nukkit.event.player.PlayerModalFormResponseEvent'Eventを渡すことができませんでした: net.comorevi.nukkitplugin.advancedwarpsystem.FormListenerでのnull"
10:31:08 [ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:568)
        at cn.nukkit.Player.handleDataPacket(Player.java:3586)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at cn.nukkit.network.Network.processPackets(Network.java:264)
        at cn.nukkit.network.Network.processBatch(Network.java:246)
        at cn.nukkit.Player.handleDataPacket(Player.java:2228)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:170)
        at cn.nukkit.Server.tick(Server.java:1519)
        at cn.nukkit.Server.tickProcessor(Server.java:1292)
        at cn.nukkit.Server.start(Server.java:1271)
        at cn.nukkit.Server.<init>(Server.java:700)
        at cn.nukkit.Nukkit$1.call(Nukkit.java:79)
        at cn.nukkit.Nukkit$1.call(Nukkit.java:76)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
        at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
        at java.base/java.util.HashMap$KeyIterator.next(Unknown Source)
        at cn.nukkit.Player.switchLevel(Player.java:935)
        at cn.nukkit.entity.Entity.setPosition(Entity.java:1828)
        at cn.nukkit.entity.Entity.setPositionAndRotation(Entity.java:1771)
        at cn.nukkit.entity.Entity.teleport(Entity.java:1961)
        at cn.nukkit.Player.teleport(Player.java:4748)
        at cn.nukkit.entity.Entity.teleport(Entity.java:1935)
        at cn.nukkit.entity.Entity.teleport(Entity.java:1931)
        at net.comorevi.nukkitplugin.advancedwarpsystem.AdvancedWarpSystem.teleportPlayer(AdvancedWarpSystem.java:40)
        at net.comorevi.nukkitplugin.advancedwarpsystem.FormListener.onEnterWindow(FormListener.java:22)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 21 more

**Comment by popkechupki** [comment]
Jupiterのエラーでした。修正待って解決に。
